### ISSUE TITLE
Feature Request: Custom symbol loading logic

### ISSUE THREAD

**Issue by sunkin351** [Firwood-Software/AdvancedDLSupport#83]
I'm wish to use ADL for loading OpenGL. Current logic uses `wglGetProcAddress` (Exported from the main library) as a backup when the primary method for loading a symbol fails. Can I replicate this with ADL? (This lets me support OGL extensions which are not exported from the main library)

**Comment by Nihlus** [comment]
This specific use case has been in the back of my mind while designing the API, and internally, it is possible to do this. Unfortunately, I haven't had time to expose the API that allows this yet. 

However, principally, it would involve writing your own method generation stage, implementing the logic there, and then injecting that stage into the pipeline. That being said, I'd like to make something a little more user-friendly than that.

Whether that's supporting injection of the platform loader in use or supporting injecting stages into the builder is up in the air, but it's definitely something I want to support.

**Comment by sunkin351** [comment]
I think the platform library loading logic is good. Perhaps you could add a way for us to set a delegate for custom logic for symbol loading.

**Comment by Nihlus** [comment]
Allowing some sort of fallback would be nice. Perhaps an IPlatformLoader that the user can provide to the builder, which would be used if either library or symbol loading fails. I'd love some API proposals in addition to the ones I have in mind :)

**Comment by sunkin351** [comment]
While we are on the subject of IPlatformLoader, in your `PlatformLoaderBase` class, you can combine your `LoadLibrary()` and `abstract LoadLibraryInternal()` into `abstract LoadLibrary()` and nothing would really change fundamentally. I put this forward to reduce Indirect and v-table method lookup.

**Comment by sunkin351** [comment]
What do you think about letting users implement a wrapper around the library loading mechanism? Or separating library and symbol loading to a degree, so we can wrap symbol loading specifically.

**Comment by sunkin351** [comment]
Would it be alright if I tried making a PR for this?

**Comment by Nihlus** [comment]
Absolutely! Contributions are always welcome :)

**Comment by Nihlus** [comment]
I'd suggest doing a rough sketch of your proposed API in your PR first, so we can work out how we want it to look.

**Comment by Perksey** [comment]
This can now be closed.
